2018-05-27 23:16:18,218:qtcode.testview:DEBUG:testview is initialized
2018-05-27 23:16:18,251:qtcode.exampleview:DEBUG:exampleview created
2018-05-27 23:16:21,756:qtcode.testview:DEBUG:testFail (test2.MyTestCase) is added
2018-05-27 23:16:21,757:qtcode.testview:DEBUG:testFail2 (test2.MyTestCase) is added
2018-05-27 23:16:21,757:qtcode.testview:DEBUG:testFail3 (test2.MyTestCase) is added
2018-05-27 23:16:21,757:qtcode.testview:DEBUG:testTrue (test2.MyTestCase) is added
2018-05-27 23:16:21,757:qtcode.testview:DEBUG:testTrue2 (test2.MyTestCase) is added
2018-05-27 23:16:26,144:consoleview:INFO:teadown class....
2018-05-27 23:16:26,159:consoleview:INFO:<qtcode.testview.TestResult run=1 errors=0 failures=1>
2018-05-27 23:16:26,166:consoleview:INFO:(<test2.MyTestCase testMethod=testFail3>, 'Traceback (most recent call last):\n  File "C:\\Users\\seoung\\workspace\\pytool\\pydevtoolplatform\\testscript\\test2.py", line 31, in testFail3\n    assert False\nAssertionError\n') 15 ms
2018-05-27 23:16:28,865:consoleview:INFO:teadown class....
2018-05-27 23:16:28,868:consoleview:INFO:teadown class....
2018-05-27 23:16:28,870:consoleview:INFO:teadown class....
2018-05-27 23:16:28,878:consoleview:INFO:teadown class....
2018-05-27 23:16:28,880:consoleview:INFO:teadown class....
2018-05-27 23:16:28,883:consoleview:INFO:<qtcode.testview.TestResult run=5 errors=0 failures=3>
2018-05-27 23:16:28,886:consoleview:INFO:testTrue2 (test2.MyTestCase) 3 ms
2018-05-27 23:16:28,889:consoleview:INFO:testTrue (test2.MyTestCase) 2 ms
2018-05-27 23:16:28,891:consoleview:INFO:(<test2.MyTestCase testMethod=testFail3>, 'Traceback (most recent call last):\n  File "C:\\Users\\seoung\\workspace\\pytool\\pydevtoolplatform\\testscript\\test2.py", line 31, in testFail3\n    assert False\nAssertionError\n') 8 ms
2018-05-27 23:16:28,896:consoleview:INFO:(<test2.MyTestCase testMethod=testFail2>, 'Traceback (most recent call last):\n  File "C:\\Users\\seoung\\workspace\\pytool\\pydevtoolplatform\\testscript\\test2.py", line 26, in testFail2\n    assert False\nAssertionError\n') 2 ms
2018-05-27 23:16:28,901:consoleview:INFO:(<test2.MyTestCase testMethod=testFail>, 'Traceback (most recent call last):\n  File "C:\\Users\\seoung\\workspace\\pytool\\pydevtoolplatform\\testscript\\test2.py", line 21, in testFail\n    assert False\nAssertionError\n') 3 ms
